-- MySQL Script generated by MySQL Workbench
-- Mon Jul  8 22:33:25 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema healthdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema healthdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `healthdb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `healthdb` ;

-- -----------------------------------------------------
-- Table `healthdb`.`clinics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `healthdb`.`clinics` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `clinicName` VARCHAR(100) NULL DEFAULT NULL,
  `clinicAddr` VARCHAR(255) NULL DEFAULT NULL,
  `LatCoords` FLOAT NULL DEFAULT NULL,
  `LonCoords` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `healthdb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `healthdb`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NULL DEFAULT NULL,
  `lastName` VARCHAR(45) NULL DEFAULT NULL,
  `userName` VARCHAR(45) NULL DEFAULT NULL,
  `passWord` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
